### ISSUE TITLE
Can't scroll faster on the documentation pages

### ISSUE THREAD

**Issue by lilydjwg** [lusakasa/saka-key#195] opened 2018-05-07 03:52 UTC
e.g. on https://key.saka.io/dev_docs/software_architecture, keys to scroll up or down (j/k) work, but keys to scroll page up / down don't. (Firefox's bultin space to scroll page down works too.)

**Comment by joefiesta** [comment] 2018-05-07 16:58
that's because that page is a help file.  Offline it would be a .chm file.  I do not know the correct terminology for what the page is.  But, AFAIK, all such pages are--quite like the Firefox about:xxxx pages, etc--not handled by SakaKey.    (If I wrong, someone please correct.   It's not a .htm address, but sure looks like a .chm (.htm?) file.)

**Comment by neilmacintyre** [comment] 2018-10-30 18:14
Saka-key will not work on webpages that Firefox does not load content scripts into:

> Note that content scripts are blocked on the following domains: accounts-static.cdn.mozilla.net, accounts.firefox.com, addons.cdn.mozilla.net, addons.mozilla.org, api.accounts.firefox.com, content.cdn.mozilla.net, content.cdn.mozilla.net, discovery.addons.mozilla.org, input.mozilla.org, install.mozilla.org, oauth.accounts.firefox.com, profile.accounts.firefox.com, support.mozilla.org, sync.services.mozilla.com, and testpilot.firefox.com. If you try to inject a content script into a page in these domains, it will fail and the page will log a CSP err

The link that you provided does not match any of those links so it should not be an issue. Also I do not experience the issue you describe. This is late response but if you could provide any details on reproducibility that would be great. Otherwise I am going to close the issue.

**Closed** 2018-10-30 18:14 UTC
