### ISSUE TITLE
Feature request: Focus on the first input field

### ISSUE THREAD

**Issue by wnereiz** [lusakasa/saka-key#73] opened 2017-10-11 03:28 UTC
vimFx and Vimium have the function to focus on the first input field with default key binding "gi". That feature is pretty handy.  Since vimium has already implemented it, so I think it is also possible for sakakey.

Thank you!

**Comment by wnereiz** [comment] 2017-10-11 03:34
One tip is to use:

`$("#formId input:text, #formId textarea").first().focus();`

I'm not sure if it works, I haven't try it. I found it from: https://stackoverflow.com/questions/4026091/jquery-dynamically-focus-on-the-first-input-or-textarea

**Comment by alexherbo2** [comment] 2017-10-11 08:31
A more general approach would be to leverage the Hint mode to apply on the input fields, and auto-validate when remains a single candidate.

**Comment by eejdoowad** [comment] 2017-10-12 07:13
Thanks for the info @wnereiz.

@alexherbo2, generalizing hints mode to make this possible is an interesting idea.  I've actually been redesigning hints mode such that you can specify which elements are hintable and what action to take once a target is selected. Implementing this would require the ability to customize how/when hint target(s) are selected.

Closing since this is a duplicate of #56.

**Closed by eejdoowad** 2017-10-12 07:13 UTC
