### ISSUE TITLE
Feature Request: whitelist

### ISSUE THREAD

**Issue by bsnsk** [lusakasa/saka-key#74] opened 2017-10-11 21:09 UTC
Can we add a whitelist feature so that sites like google calendar or gmail can use their own shortcuts?

**Comment by eejdoowad** [comment] 2017-10-12 07:25
This is actually a duplicate of #42. A short-term work is to use the pass keys commands. (https://key.saka.io/tutorial/pass_keys)[https://key.saka.io/tutorial/pass_keys)

**Closed** 2017-10-12 07:26 UTC
